### ISSUE TITLE
How to change size / color?

### ISSUE THREAD

**Issue by alpapp** [kalimah-apps/vue-icons#3]
Lovely idea!  Your intro text says "Stylable. You can change color and size of the icons" - I'm just trying to figure out how to change the icon size.  I've tried:

```
<BsCalendar4Range class="w-4" />
<BsCalendar4Range style="width: 4em;" />
<BsCalendar4Range width="4em" />
```

But can't get the size to change.  I see the SVG seems hardcoded at 1em?

Many thanks for any advice.

**Comment by abdul-alhasany** [comment]
Thanks for the question.
You can change the size with font-size property:
```vue
<BsCalendar4Range style="font-size: 2em" />
```

I will later add documentation to showcase the styling aspect.
