### ISSUE TITLE
Tree-shaking doesn't seem to be working?

### ISSUE THREAD

**Issue by fxjs** [kalimah-apps/vue-icons#5]
Problem screenshot：

![image](https://github.com/kalimahapps/vue-icons/assets/3682415/9b188b69-8ad2-4da4-bd60-438ec19fdca5)

```js
import { CaLocationFilled as LocationIcon } from '@kalimahapps/vue-icons';
```
```vue template
<LocationIcon />
```

Technology Stack: vue3、webpack5(use vue-cli).

**Thank you very much for the author's efforts. This library is great, and I hope to use it better in the project. I hope tree shaking can work well.**

**Comment by abdul-alhasany** [comment]
Welcome here.

Are you using webpack or vite? 
Do you have an example repo so I can have a look.

**Comment by fxjs** [comment]
> 

webpack5

**Comment by abdul-alhasany** [comment]
I developed the library using vite. So I have never tested on webpack. Do you have an online repo I can test on?

**Comment by fxjs** [comment]
DEMO：[demo-webpack5.zip](https://github.com/kalimahapps/vue-icons/files/11641628/demo-webpack5.zip)

```js
pnpm i && pnpm run dev
```

It is also possible that it is just a warning displayed by Babel, occasionally appearing.

![image](https://github.com/kalimahapps/vue-icons/assets/3682415/0d56a86d-6729-4ba5-b421-012ad1e89b48)

**Comment by abdul-alhasany** [comment]
Thanks for the demo. I will have a look. 

> It is also possible that it is just a warning displayed by Babel, occasionally appearing.

Yes. the second screenshot you sent shows the build is ~3kb. If the tree shaking was not applied it will be 40MB+ :)

**Comment by abdul-alhasany** [comment]
@fxjs 
I finally was able to debug the issue. If you use `compact: true` option you will get rid of the error. Using this option 

> Babel won't emit superfluous whitespace characters or line terminators. It will, however, retain comments. **The idea is that if the transpiled JavaScript code is minified afterwards anyway, there's no need for neat formatting**.

Form : https://mariusschulz.com/blog/speeding-up-babel-transpilation-with-compact-mode. (emphasis is mine).

I think the issue is related to styling so using this option will ignore the the file before build and will format/minify/process after a build. And as a good side effect you get faster bundling time.

You can check the option details here:
https://babeljs.io/docs/options#compact

**Comment by fxjs** [comment]
Can you share how to configure `compact: true` in my `DEMO` project? thanks

**Comment by abdul-alhasany** [comment]
In babel.config.js, like so:
```
module.exports = {
  presets: ['@vue/cli-plugin-babel/preset'],
  compact: true,
};
```

**Comment by fxjs** [comment]
> In babel.config.js, like so:
> 
> ```
> module.exports = {
>   presets: ['@vue/cli-plugin-babel/preset'],
>   compact: true,
> };
> ```

Thank you so much for your assistance, that solution was perfect.
