### ISSUE TITLE
Icons are not displaying on the Website

### ISSUE THREAD

**Issue by harryparkinson101** [kalimah-apps/vue-icons#6]
I love using this package for my icons, just a heads-up that the icons are not showing correctly.

![image](https://github.com/kalimahapps/vue-icons/assets/71083434/c98ca265-da49-4878-908f-dbb14d81f78d)

Everything shows up in white when i click an icon: 

![image](https://github.com/kalimahapps/vue-icons/assets/71083434/172372c2-0f05-44ce-a462-32d97fbcec86)

this is on linux, firefox browser. I have yet to try other devices or browsers.

UPDATE: I have tried on Chrome and I get the same result

**Comment by abdul-alhasany** [comment]
Thanks for the notice. I fixed the issue.
